package Banque;


/**
* Banque/java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* mercredi 17 novembre 2021 11 h 21 WEST
*/

public interface Banque extends BanqueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Banque
